[package]
name = "file-analysis"
version = "0.1.0"
edition = "2021"


[dependencies]
jwalk = "0.8.1"
zip = "0.6.6"
sha2 = "0.10.8"
futures = "0.3.30"
tokio = { version = "1.36.0", features = ["full"] }
