version: "3.8"

services:
  py-ts-rust:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - C:\Users\Marko\.aws:/root/.aws
    command: sleep infinity
    environment:
      WATCHPACK_POLLING: "true"
